-- DATABASE CREATION 
use master 
IF EXSISTS (SELECT = FROM sys.databases WHERE name = 'SMSDBGR2' ) 
DROP DATABASE SMSDBGR2 
CREATE DATABASE SMSDBGR2 
use SMSDBGR2

--TABLE CREATION SECTION 
CREATE TABLE Student (
StudentID INT NOT NULL, 
STNumber VARCHAR(10) NOT NULL, 
FullName VARCHAR (MAX) NOT NULL
); 

CREATE TABLE Module ( 
ModuleID INT PRIMARY KEY NOT NULL, 
Qualification VARCHAR (50), 
Code VARCHAR (8) 
); 

CREATE TABLE Enrollment (
EnrollmentID INT PRIMARY KEY NOT NULL, 
)

--/-- TABLE ALTERATION SECTION 


-- TABLE CREATION SECTION 
-- 
